CREATE DATABASE db_Marketplace;

USE db_Marketplace;

CREATE TABLE USERS(
    UNAME VARCHAR(16) NOT NULL,
    LASTNAME VARCHAR(16) NOT NULL,
    ID INT(11) NOT NULL primary key,
    TIDENT VARCHAR(20) NOT NULL,
    EMAIL VARCHAR (40) NOT NULL,
    password VARCHAR(100) NOT NULL,
    TELEPHONE VARCHAR (16) NOT NULL,
    DIRECTION VARCHAR (70) NOT NULL
);

CREATE TABLE PRODUCTS(
    ID INT(12) NOT NULL primary key,
    PNAME VARCHAR(50) NOT NULL,
    PRICE INT(12) NOT NULL,
    GENDER VARCHAR (15) NOT  NULL,
    COLOR VARCHAR (16) NOT NULL,
    SIZE VARCHAR (16) NOT NULL,
    STOCK INT (16) NOT NULL 
);
